core/urls.py
# -*-coding:utf-8 -*-
"""
:module: core.urls
:synopsis: root URL for core

:moduleauthor: anthony greau <greau.anthony@gmail.com>
:created: 01/07/2015
:update: 21/07/2015
:var urlpatterns: rooting of urls
"""
from django.conf.urls import patterns
from django.conf.urls import url

from core import home

urlpatterns = patterns('',
                       url(r'^', home.index, name="home"),
                       )

framework/urls.py
from django.conf import settings
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = patterns('',
                       url(r'^$', include('core.urls')),
                       url(r'', include('contact.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^forum/', include('forum.urls')),
                       url(r'^hijack/', include('hijack.urls')),
                       url(r'^i18n/', include('django.conf.urls.i18n')),
                       url(r'^issue/', include('issues.urls')),
                       url(r'^ldap/', include('ldap42.urls')),
                       url(r'^log/', include('generate_logs.urls')),
                       url(r'^profil/', include('profil.urls')),
                       ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.MEDIA_ROOT})
                            )

ldap42/urls.py
from django.conf.urls import patterns
from django.conf.urls import url

from ldap42 import views

urlpatterns = patterns('',
                       url(r'^$', views.login_ldap, name="login_ldap"),
                       url(r'^annuaire/(?P<order>.+)/(?P<letter>.+)/$', views.ldap_display,
                           name="ldap_display_filter"),
                       )

ldap42/models.py
# Create your models here.

ldap42/forms/LdapForm.py
# -*-coding:utf-8 -*-
import datetime

from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _


class LdapForm(forms.Form, forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password',
        ]

    login = forms.CharField(
        label=_("login42"),
        widget=forms.TextInput(
            attrs={
                'class': "form-control",
                'placeholder': _("login42"),
            },
        ),
    )
    password = forms.CharField(
        label=_("password"),
        widget=forms.PasswordInput(
            attrs={
                'class': "form-control",
                'placeholder': _("password")
            },
        ),
    )

    pool_month = forms.ChoiceField(
        label=_("pool_month"),
        choices=[
            ('july', _('juillet')),
            ('august', _('aout')),
            ('september', _('septembre')),
            ('october', _('octobre'))
        ],
        widget=forms.Select(
            attrs={
                'class': 'selector',
                'class': "form-control",
                'placeholder': _("pool_month")
            }
        ),
    )

    date_now = datetime.datetime.now()
    year = 2013
    years = []
    while year <= date_now.year:
        years.append((year, year))
        year += 1

    pool_year = forms.ChoiceField(
        label=_("pool_year"),
        choices=years,
        widget=forms.Select(
            attrs={
                'class': 'selector',
                'class': "form-control",
                'placeholder': _("pool_year")
            }
        ),
    )

ldap42/views.py
# -*-coding:utf-8 -*-

import base64
import logging
import string
from operator import itemgetter

import ldap3
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import translation
from django.contrib.auth import authenticate
from django.contrib.auth import hashers
from django.contrib.auth import login
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

from django.utils.translation import ugettext as _

from generate_logs import functions as l_fct
from ldap42.forms.LdapForm import LdapForm
from profil.functions import create_user
from profil.models import UserLang

logger_error = logging.getLogger('error')
logger_info = logging.getLogger('info')


def connect_to_ldap(session):
    s = ldap3.Server(
        'ldaps://ldap.42.fr',
        port=636,
        get_info=ldap3.ALL
    )
    c = ldap3.Connection(
        s,
        auto_bind=True,
        client_strategy='SYNC',
        user='uid={},ou={},ou={},ou=paris,ou=people,dc=42,dc=fr'.format(session['ldap_log']['login'],
                                                                        session['ldap_log'][
                                                                            'pool_month'],
                                                                        session['ldap_log']['pool_year']),
        password=session['ldap_log']['password'],
        authentication=ldap3.SIMPLE,
        check_names=True,
        raise_exceptions=False
    )
    return c


@login_required
def ldap_display(request, order, letter):
    logger_info.info(l_fct.info_load_log_message(request))
    errors = []
    alphabet = string.ascii_lowercase
    if letter != 'all' and letter not in alphabet:
        l = 'a'
    elif letter == 'all':
        l = ''
    else:
        l = letter
    c = connect_to_ldap(request.session)
    if c.bind():
        logger_info.info(l_fct.info_login_ldap_log_message(request))
        c.search(
            search_base='ou=paris,ou=people,dc=42,dc=fr',
            search_filter='(uid={}*)'.format(l),
            search_scope=ldap3.SUBTREE,
            attributes=[
                'uid',
                'givenName',
                'jpegPhoto',
                'mobile',
                'sn',
            ]
        )
        annuaire = []
        for r in c.response:
            annuaire.append(
                {
                    'avatar': base64.b64encode(r['attributes']['jpegPhoto'][0]) if 'jpegPhoto' in r[
                        'attributes'] else '',
                    'uid': r['attributes']['uid'][0],
                    'givenName': r['attributes']['givenName'][0],
                    'mobile': r['attributes']['mobile'][0] if 'mobile' in r['attributes'] else '',
                    'sn': r['attributes']['sn'][0],
                }
            )
        c.unbind()
        annuaire.sort(
            key=itemgetter('uid'), reverse=True if order == 'reverse' else False)
    else:
        logger_error.info(l_fct.error_ldap_log_message(request, "bind"))
        errors['unknow'] = _("bind_error")
    return render(
        request,
        "ldap42/ldap_display.html",
        {
            'alphabet': alphabet,
            'annuaire': annuaire,
            'form': LdapForm(),
            'letter': letter,
            'order': order,
        }
    )


def login_ldap(request):
    logger_info.info(l_fct.info_load_log_message(request))
    if request.user.is_authenticated():
        logger_error.error(l_fct.error_load_log_message(request))
        return redirect(reverse('home'))
    else:
        errors = {}
        form = LdapForm(request.POST)
        if request.method == 'POST':
            request.session['ldap_log'] = request.POST
            c = connect_to_ldap(request.session)
            if c.bind():
                logger_info.info(l_fct.info_login_ldap_log_message(request))
                c.search(
                    search_base='ou=people,dc=42,dc=fr',
                    search_filter='(uid={})'.format(request.POST['login']),
                    search_scope=ldap3.SUBTREE,
                    attributes=[
                        'uid',
                        'givenName',
                        'mobile',
                        'sn',
                        'alias'
                    ]
                )
                u = User.objects.filter(
                    username=c.response[0]['attributes']['uid'][0])
                if len(u) == 0:
                    create_user(
                        request,
                        c.response[0]['attributes']['uid'][0],
                        c.response[0]['attributes']['alias'][0],
                        request.POST['password'],
                        c.response[0]['attributes']['givenName'][0],
                        c.response[0]['attributes']['sn'][0],
                    )
                else:
                    if not hashers.check_password(request.POST['password'], u[0].password):
                        u[0].set_password(request.POST['password'])
                        u[0].save()
                user = authenticate(
                    username=request.POST['login'],
                    password=request.POST['password'],
                )
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        userlang = UserLang.objects.get(user=request.user)
                        logger_info.info(
                            l_fct.info_login_class_log_message(request))
                        translation.activate(userlang.lang)
                        request.session[
                            translation.LANGUAGE_SESSION_KEY] = userlang.lang
                        redir = reverse('home')
                        if 'next' in request.GET and request.GET['next'] != reverse('login'):
                            redir = request.GET['next']
                        return redirect(
                            redir,
                            permanent=True
                        )
                    else:
                        logger_error.error(
                            l_fct.error_login_log_message(request))
                        errors['unknow'] = _("authenticate error")
                else:
                    logger_error.error(
                        l_fct.error_login_wrong_password_log_message(request))
                    errors['pass'] = _("error_wrong_password")
                c.unbind()
            else:
                logger_error.info(
                    l_fct.error_ldap_log_message(request, "bind"))
                errors['unknow'] = _("bind_error")
        else:
            form = LdapForm()
    return render(
        request,
        "ldap42/loginldap.html",
        {
            'form': form,
            'errors': errors,
        }
    )

ldap42/templates/ldap42/ldap_display.html
{% extends "core/base.html" %}
{% load i18n %}
{% block content %}
    <nav class="text-center">
        <div>
            <ul class="pagination">
                <li{% if letter == 'all' %} class="active"{% endif %}>
                    <a href="{% url 'ldap_display_filter' order letter %}">all</a>
                </li>
                {% for l in alphabet %}
                    <li{% if letter == l %} class="active"{% endif %}>
                        <a href="{% url 'ldap_display_filter' order l %}">{{ l }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="form-group row">
            <span class="col-md-offset-4 col-md-4 col-ld-offset-4">
                <button type="button" id="natural-order" class="btn btn-default" aria-label="Left Align">
                    <span class="glyphicon glyphicon-sort-by-alphabet" aria-hidden="true"></span>
                </button>
                <button type="button" id="reverse-order" class="btn btn-default" aria-label="Left Align">
                    <span class="glyphicon glyphicon-sort-by-alphabet-alt" aria-hidden="true"></span>
                </button>
            </span>
        </div>
    </nav>
    <table class="table">
        <thead>
        <tr>
            <th></th>
            <th>{% trans 'login42'|capfirst %}</th>
            <th>{% trans 'prenom'|capfirst %}</th>
            <th>{% trans 'nom'|capfirst %}</th>
            <th>{% trans 'phone'|capfirst %}</th>
        </tr>
        </thead>
        {% for user in annuaire %}
            <tr>
                <td>
                    <img src="
                        {% if user.avatar %}
                            data:image/jpeg;base64,{{ user.avatar }}
                        {% else %}
                            http://thumbs.dreamstime.com/x/avatar-inconnu-d-homme-d-affaires-35616527.jpg
                        {% endif %}
                    " class="img-circle" height="50" widtrh="50">
                </td>
                <td>{{ user.uid }}</td>
                <td>{{ user.givenName }}</td>
                <td>{{ user.sn }}</td>
                <td>{{ user.mobile }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
            var split_url = location.pathname.split('/');
            $('#natural-order').click(function () {
                if (split_url[3] == 'reverse') {
                    url = location.pathname.replace("reverse", "natural");
                    window.location.href = url;
                }
            });
            $('#reverse-order').click(function () {
                if (split_url[3] == 'natural') {
                    url = location.pathname.replace("natural", "reverse");
                    window.location.href = url;
                }
            });
        });
    </script>
{% endblock %}

ldap42/templates/ldap42/loginldap.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'home'|capfirst %}</a></li>
        <li><a href="{% url 'login' %}">{% trans 'login'|capfirst %}</a></li>
        <li class="active">{% trans 'connection_ldap'|capfirst %}</li>
    </ol>
    {% if errors %}
        {% for k, v in errors.items %}
            <div class="alert alert-danger" role="alert">
                {{ v }}
            </div>
        {% endfor %}
    {% endif %}
    {% if errors.admin or errors.staff %}
        <form action="{% url 'login_ldap' %}" method="post">
    {% elif request.GET.next == url_logout %}
        <form action="{% url 'login_classic' %}?next={{ url_home }}" method="post">
    {% elif equest.GET.next %}
        <form action="{{ request.META.HTTP_REFERER }}" method="post">
    {% else %}
        <form action="{% url 'login_ldap' %}?next={{ request.get_full_path }}" method="post">
    {% endif %}
{% csrf_token %}
<div class="form-group">
    <label for="id_login">{{ form.login.label|capfirst }} </label>
    {{ form.login }}
</div>
{% if errors.username %}
    <p class="alert alert-danger" role="alert">{{ errors.user|capfirst }}</p>
{% endif %}
<div class="form-group">
    <label for="id_password">{% trans 'password'|capfirst %} </label>
    {{ form.password }}
</div>
{% if errors.pass %}
    <p class="alert alert-danger" role="alert">{{ errors.pass|capfirst }}</p>
{% endif %}
<div class="form-group row">
    <div class="col-md-6">
        <label for="id_pool_month">{% trans 'pool_month'|capfirst %} </label>
        {{ form.pool_month }}
    </div>
    <div class="col-md-6">
        <label for="id_pool_year">{% trans 'pool_year'|capfirst %} </label>
        {{ form.pool_year }}
    </div>
</div>
<div class="form-group">
    <input type="submit" value="{% trans 'connexion'|capfirst %}" class="btn btn-primary btn-lg btn-block"/>
</div>
</form>
{% endblock %}