core/urls.py
# -*-coding:utf-8 -*-
"""
:module: core.urls
:synopsis: root URL for core

:moduleauthor: anthony greau <greau.anthony@gmail.com>
:created: 01/07/2015
:update: 21/07/2015
:var urlpatterns: rooting of urls
"""
from django.conf.urls import patterns
from django.conf.urls import url

from core import home

urlpatterns = patterns('',
                       url(r'^', home.index, name="home"),
                       )

framework/urls.py
from django.conf import settings
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = patterns('',
                       url(r'^$', include('core.urls')),
                       url(r'', include('contact.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^forum/', include('forum.urls')),
                       url(r'^hijack/', include('hijack.urls')),
                       url(r'^i18n/', include('django.conf.urls.i18n')),
                       url(r'^issue/', include('issues.urls')),
                       url(r'^ldap/', include('ldap42.urls')),
                       url(r'^log/', include('generate_logs.urls')),
                       url(r'^profil/', include('profil.urls')),
                       ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.MEDIA_ROOT})
                            )

profil/urls.py
from django.conf.urls import url

from profil import views

urlpatterns = [
    url(r'^register', views.register_user, name="register"),
    url(r'^login', views.select_login, name="login"),
    url(r'^local', views.login_user, name="login_classic"),
    url(r'^logout', views.logout_user, name="logout"),
]

profil/models.py
from django.db import models
from django.contrib.auth.models import User


class UserLang(models.Model):
    user = models.ForeignKey(User)
    lang = models.CharField(max_length=3)

profil/forms/LogInForm.py
# -*-coding:utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _


class LogInForm(forms.Form, forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password',
        ]

    username = forms.CharField(
        label=_("username"),
        widget=forms.TextInput(
            attrs={
                'class': "form-control",
                'placeholder': _("username"),
            },
        ),
    )
    password = forms.CharField(
        label=_("password"),
        widget=forms.PasswordInput(
            attrs={
                'class': "form-control",
                'placeholder': _("password")
            },
        ),
    )

profil/forms/RegisterForm.py
# -*-coding:utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _


class RegisterForm(forms.Form, forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password',
        ]

    username = forms.CharField(
        required=True,
        label=_("username"),
        widget=forms.TextInput(
            attrs={
                'class': "form-control",
                'placeholder': _("username")
            },
        ),
    )
    email = forms.EmailField(
        required=True,
        label=_("mail_adress"),
        widget=forms.TextInput(
            attrs={
                'class': "form-control",
                'placeholder': _("mail_adress")
            },
        ),
    )
    password = forms.CharField(
        required=True,
        label=_("password"),
        widget=forms.PasswordInput(
            attrs={
                'class': "form-control",
                'placeholder': _("password")
            },
        ),
    )
    password_conf = forms.CharField(
        required=True,
        label=_("password_conf"),
        widget=forms.PasswordInput(
            attrs={
                'class': "form-control",
                'placeholder': _("password_conf")
            },
        ),
    )

profil/views.py
# -*-coding:utf-8 -*-
import logging

from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import translation
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from contact import contact
from generate_logs import functions as l_fct
from profil.functions import create_user
from profil.models import UserLang
from profil.forms.LogInForm import LogInForm
from profil.forms.RegisterForm import RegisterForm

logger_error = logging.getLogger('error')
logger_info = logging.getLogger('info')


def register_user(request):
    logger_info.info(l_fct.info_load_log_message(request))
    if request.user.is_authenticated():
        logger_error.error(l_fct.error_load_log_message(request))
        return redirect(
            request.META[
                'HTTP_REFERER'] if "HTTP_REFERER" in request.META else reverse('home'),
            permanent=True
        )
    else:
        errors = {}
        form = RegisterForm(request.POST)
        if request.method == 'POST' and len(request.POST):
            email_exist = User.objects.filter(email=request.POST['email'])
            user_exist = User.objects.filter(username=request.POST['username'])
            if len(user_exist) > 0:
                logger_error.error(l_fct.error_register_user_exist(request))
                errors['user'] = _("error_user_already_exist")
            if len(email_exist) > 0:
                logger_error.error(l_fct.error_register_mail_exist(request))
                errors['mail'] = _("error_mail_already_exist")
            if request.POST['password'] != request.POST['password_conf']:
                errors['pass'] = _("error_wrong_password")
            if len(errors) == 0 and form.is_valid():
                create_user(
                    request,
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )
                user = authenticate(
                    username=form.cleaned_data['username'],
                    password=form.cleaned_data['password'],
                )
                redir = reverse('home')
                if 'next' in request.GET and request.GET['next'] != reverse('login'):
                    redir = request.GET['next']
                login(request, user)
                return redirect(
                    redir,
                    permanent=True
                )
            elif len(errors) == 0:
                errors['form'] = _("unknow_error_register_form")
        return render(
            request,
            "profil/register.html",
            {
                'form': form,
                'errors': errors,
                'formcontact': contact.ContactForm(),
            }
        )


def select_login(request):
    logger_info.info(l_fct.info_load_log_message(request))
    return render(
        request,
        "profil/login.html",
        {
            'type': "select",
        }
    )


def login_user(request):
    logger_info.info(l_fct.info_load_log_message(request))
    if request.user.is_authenticated():
        logger_error.error(l_fct.error_load_log_message(request))
        return redirect(
            request.META[
                'HTTP_REFERER'] if "HTTP_REFERER" in request.META else reverse('home'),
            permanent=True
        )
    else:
        errors = {}
        form = LogInForm(request.POST)
        if request.method == 'POST' and len(request.POST):
            user_exist = User.objects.filter(username=request.POST['username'])
            if len(user_exist) == 0:
                logger_error.error(
                    l_fct.error_inexistant_user_log_message(request))
                errors['user'] = _("error_user_not_exist")
            else:
                if len(errors) == 0:
                    if 'user' not in errors:
                        user = authenticate(
                            username=request.POST['username'],
                            password=request.POST['password'],
                        )
                        if user is not None:
                            if user.is_active:
                                login(request, user)
                                if request.user.is_staff or request.user.is_superuser:
                                    try:
                                        userlang = UserLang.objects.get(user=request.user)
                                    except:
                                        UserLang(user=user, lang=translation.get_language()).save()
                                        userlang = UserLang.objects.get(user=request.user)
                                else:
                                    userlang = UserLang.objects.get(user=request.user)
                                logger_info.info(l_fct.info_login_class_log_message(request))
                                translation.activate(userlang.lang)
                                request.session[translation.LANGUAGE_SESSION_KEY] = userlang.lang
                                request.session['ldap_connection'] = False
                                redir = reverse('home')
                                if 'next' in request.GET and request.GET['next'] != reverse('login'):
                                    redir = request.GET['next']
                                return redirect(
                                    redir,
                                    permanent=True
                                )
                            else:
                                logger_error.error(
                                    l_fct.error_login_log_message(request))
                                errors['unknow'] = _("authenticate error")
                        else:
                            logger_error.error(
                                l_fct.error_login_wrong_password_log_message(request))
                            errors['pass'] = _("error_wrong_password")
                    else:
                        logger_error.error(
                            l_fct.error_login_unknow_log_message(request))
                        errors['unknow'] = _("unknow error")
    return render(
        request,
        "profil/login.html",
        {
            'form': form,
            'errors': errors,
            'type': "classic",
            'formcontact': contact.ContactForm(),
        }
    )


@login_required
def logout_user(request):
    logger_info.info(l_fct.info_load_log_message(request))
    cur_language = translation.get_language()
    userlang = UserLang.objects.get(user=request.user)
    if userlang.lang is not cur_language:
        userlang.lang = cur_language
        userlang.save()
    redir = request.META[
        'HTTP_REFERER'] if "HTTP_REFERER" in request.META else reverse('home')
    if logout(request):
        logger_info.info(l_fct.info_logout_log_message(request))
    else:
        logger_error.info(l_fct.error_logout_log_message(request))
    return redirect(
        redir,
        permanent=True
    )

profil/templates/profil/login.html
{% extends 'core/base.html' %}
{% load i18n %}

{% block content %}
    {% if type == "select" %}
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">{% trans 'home'|capfirst %}</a></li>
            <li class="active">{% trans 'login'|capfirst %}</li>
        </ol>
        <div class="jumbotron">
            <div class="container">
                <div class="row">
                    <button type="button" class="btn btn-lg btn-block"><a
                            href="{% url 'login_classic' %}">{% trans 'login_classic'|capfirst %}</a></button>
                    <button type="button" class="btn btn-lg btn-block"><a
                            href="{% url 'login_ldap' %}">{% trans 'login_ldap'|capfirst %}</a></button>
                </div>
            </div>
        </div>
    {% elif type == "classic" %}
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">{% trans 'home'|capfirst %}</a></li>
            <li><a href="{% url 'login' %}">{% trans 'login'|capfirst %}</a></li>
            <li class="active">{% trans 'connection_classic'|capfirst %}</li>
        </ol>
        {% if errors %}
            {% for k, v in errors.items %}
                <div class="alert alert-danger" role="alert">
                    {{ v }}
                </div>
            {% endfor %}
        {% endif %}
        {% if errors.admin or errors.staff %}
            <form action="{% url 'login_classic' %}" method="post">
        {% elif request.GET.next == url_logout %}
            <form action="{% url 'login_classic' %}?next={{ url_home }}" method="post">
        {% elif request.GET.next %}
            <form action="{{ request.META.HTTP_REFERER }}" method="post">
        {% else %}
            <form action="{% url 'login_classic' %}?next={{ request.get_full_path }}" method="post">
        {% endif %}
    {% csrf_token %}
    <div class="form-group">
        <label for="id_username">{{ form.username.label|capfirst }} </label>
        {{ form.username }}
    </div>
    {% if errors.username %}
        <p class="alert alert-danger" role="alert">{{ error.user|capfirst }}</p>
    {% endif %}
    <div class="form-group">
        <label for="id_password">{% trans 'password'|capfirst %} </label>
        {{ form.password }}
    </div>
    {% if errors.pass %}
        <p class="alert alert-danger" role="alert">{{ errors.pass|capfirst }}</p>
    {% endif %}
    <div class="form-group">
        <input type="submit" value="{% trans 'connexion'|capfirst %}" class="btn btn-primary btn-lg btn-block"/>
    </div>
    </form>
    {% endif %}
{% endblock %}

profil/templates/profil/register.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block content %}
    <div class="jumbotron">
        {% if errors %}
            {% for k, v in errors.items %}
                <div class="alert alert-danger" role="alert">
                    {{ v }}
                </div>
            {% endfor %}
        {% endif %}
        {% if request.GET.next %}
            <form action="{{ request.META.HTTP_REFERER }}" method="post">
        {% else %}
            <form action="{% url 'register' %}?next={{ request.get_full_path }}" method="post">
        {% endif %}
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">{{ form.username.label|capfirst }} </label>
            {{ form.username }}
        </div>
        {% if error.username %}
            <p class="alert alert-danger" role="alert">{{ error.user|capfirst }}</p>
        {% endif %}
        <div class="form-group">
            <label for="id_email">{{ form.email.label|capfirst }} </label>
            {{ form.email }}
        </div>
        {% if error.email %}
            <p class="alert alert-danger" role="alert">{{ error.email|capfirst }}</p>
        {% endif %}
        <div class="form-group">
            <label for="id_password">{% trans 'password'|capfirst %} </label>
            {{ form.password }}
        </div>
        {% if error.pass %}
            <p class="alert alert-danger" role="alert">>{{ error.pass|capfirst }}</p>
        {% endif %}
        <div class="form-group">
            <label for="id_password_conf">{% trans 'password_conf'|capfirst %} </label>
            {{ form.password_conf }}
        </div>
        {% if error.pass %}
            <p class="alert alert-danger" role="alert">>{{ error.pass|capfirst }}</p>
        {% endif %}
        <div class="form-group">
            <input type="submit" value="{% trans 'register'|capfirst %}" class="btn btn-primary btn-lg btn-block"/>
        </div>
        </form>
    </div>
{% endblock %}