core/urls.py
# -*-coding:utf-8 -*-
"""
:module: core.urls
:synopsis: root URL for core

:moduleauthor: anthony greau <greau.anthony@gmail.com>
:created: 01/07/2015
:update: 21/07/2015
:var urlpatterns: rooting of urls
"""
from django.conf.urls import patterns
from django.conf.urls import url

from core import home

urlpatterns = patterns('',
                       url(r'^', home.index, name="home"),
                       )

framework/urls.py
from django.conf import settings
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = patterns('',
                       url(r'^$', include('core.urls')),
                       url(r'', include('contact.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^forum/', include('forum.urls')),
                       url(r'^hijack/', include('hijack.urls')),
                       url(r'^i18n/', include('django.conf.urls.i18n')),
                       url(r'^issue/', include('issues.urls')),
                       url(r'^ldap/', include('ldap42.urls')),
                       url(r'^log/', include('generate_logs.urls')),
                       url(r'^profil/', include('profil.urls')),
                       ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.MEDIA_ROOT})
                            )

issues/urls.py
# -*-coding:utf-8 -*-
"""
:module: issues.urls
:synopsis: root URL for issues

:moduleauthor: anthony greau <greau.anthony@gmail.com>
:created: 01/07/2015
:update: 21/07/2015
:var urlpatterns: rooting of urls
"""
from django.conf.urls import patterns
from django.conf.urls import url

from issues import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name="list_issue"),
                       url(r'^respond/(?P<issue>.+)/$',
                           views.respond_issue, name="respond_issue"),
                       url(r'^reopen/(?P<issue>.+)/$',
                           views.reopen_issue, name="reopen_issue"),
                       url(r'^view/(?P<issue>.+)/$',
                           views.view_issue, name="view_issue"),
                       url(r'^new_issue/$', views.new_issue, name="new_issue"),
                       )

issues/models.py
# -*-coding:utf-8 -*-
"""
:module: Issues.models
:synopsis: define storage models for issues

:moduleauthor: anthony greau <greau.anthony@gmail.com>
:created: 01/07/2015
:update: 05/08/2015
"""
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

from autoslug import AutoSlugField


class Issue(models.Model):
    """define the storage of category

    :param models.Model: contain all function for define a storage
    :type models.Model: models object
    :var Autor: User object contain autor of request
    :var Assign: User object contain staff member in charge
    :var Title: Title of Issue
    :var UserRequest: Content of Issue
    :var Answer: Staff response to UserRequest
    :var CreateDate: Create date of issue
    :var LastActivity: date of last activity
    :var Status: status of issue (open/in progress/close)
    :return: Issue object
    :rtype: object
    """
    Autor = models.ForeignKey(User)
    Assign = models.ForeignKey(
        User,
        related_name=_("assign_to"),
        null=True,
    )
    Title = models.CharField(
        max_length=100
    )
    slug = AutoSlugField(populate_from='Title')
    UserRequest = models.TextField()
    Answer = models.TextField()
    CreateDate = models.DateTimeField(auto_now_add=True)
    LastActivity = models.DateTimeField(auto_now_add=True)
    Status = models.CharField(
        max_length=20,
        default="open",
        choices=(
            ("open", _("open")),
            ("progress", _("in_progress")),
            ("close", _("close")),
        )
    )

    def __str__(self):
        return self.Title

issues/forms/AdminResponseIssue.py
# -*-coding:utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

from issues.models import Issue


class AdminResponseIssueForm(forms.Form):
    class Meta:
        model = Issue
        fields = [
            'Assign',
            'Answer',
            'Status',
        ]

    admin = User.objects.filter(is_superuser=True)
    USER_LIST = []
    for a in admin:
        USER_LIST.append((a, a))

    assign = forms.ChoiceField(
        label=_("assign"),
        choices=USER_LIST,
        widget=forms.Select(
            attrs={
                'class': 'selector',
                'class': "form-control",
                'placeholder': _("assign_to")
            }
        ),
    )
    status = forms.ChoiceField(
        label=_("status"),
        choices=(
            ("open", _("open")),
            ("progress", _("in_progress")),
            ("close", _("close")),
        ),
        widget=forms.Select(
            attrs={
                'class': 'selector',
                'class': "form-control",
                'placeholder': _("status")
            }
        )
    )
    answer = forms.CharField(
        label=_("answer"),
        widget=forms.Textarea(
            attrs={
                'class': "form-control",
                'placeholder': _("answer")
            },
        ),
    )

issues/forms/SubmitIssue.py
# -*-coding:utf-8 -*-
from django import forms
from django.utils.translation import ugettext as _

from issues.models import Issue


class IssueForm(forms.Form):
    class Meta:
        model = Issue
        fields = [
            'Title',
            'UserRequest',
        ]

    Title = forms.CharField(
        label=_("title"),
        widget=forms.TextInput(
            attrs={
                'class': "form-control",
                'placeholder': _("title")
            },
        ),
    )
    UserRequest = forms.CharField(
        label=_("issue"),
        widget=forms.Textarea(
            attrs={
                'class': "form-control",
                'placeholder': _("issue")
            },
        ),
    )

issues/views.py
# -*-coding:utf-8 -*-
"""
:module: issues.views
:synopsis: generate all content of issues

:moduleauthor: anthony greau <greau.anthony@gmail.com>
:created: 01/07/2015
:update: 30/07/2015
:var logger_error: logger error
:var logger_info: logger info
:seealso: issues.models.Issue
:seealso: forum.forms.CreateTopic.TopicForm
:seealso: generate_logs.functions.info_load_log_message
:seealso: issues.forms.AdminResponseIssue.AdminResponseIssueForm
:seealso: from issues.forms.SubmitIssue.IssueFor
"""
import datetime
import logging

from django.shortcuts import redirect
from django.shortcuts import render
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from issues.models import Issue
from generate_logs.functions import info_load_log_message
from issues.forms.AdminResponseIssue import AdminResponseIssueForm
from issues.forms.SubmitIssue import IssueForm

logger_info = logging.getLogger('info')


@login_required
def index(request):
    """display the issues about the user connected

    :param request: object contain context of request
    :type request: object
    :var issues: contain issues to display
    :return: HTTPResponse
    """
    logger_info.info(info_load_log_message(request))
    if request.user.is_superuser or request.user.is_staff:
        issues = Issue.objects.all()
    else:
        issues = Issue.objects.filter(Autor=request.user)
    return render(request, 'issues/home.html', {'issues': issues})


@login_required
def new_issue(request):
    logger_info.info(info_load_log_message(request))
    form = IssueForm(request.POST)
    context = {}
    if request.POST:
        if form.is_valid():
            create = Issue(
                Autor=request.user,
                Title=form.cleaned_data['Title'],
                UserRequest=form.cleaned_data['UserRequest'],
            ).save()
        if create is None:
            issue = Issue.objects.filter(
                Title=form.cleaned_data['Title']
            ).filter(
                Autor=request.user
            ).filter(
                UserRequest=form.cleaned_data['UserRequest']
            )[0]
            return redirect(
                reverse(
                    'view_issue',
                    kwargs={
                        'issue': issue.slug,
                    }
                ),
                permanent=True
            )
        else:
            context['error'] = _('save_error')
    context['form'] = form
    return render(request, 'issues/send_issue.html', context)


@login_required
def respond_issue(request, issue):
    SelectIssue = Issue.objects.get(slug=issue)
    if (request.user.is_staff or request.user.is_superuser) is True:
        logger_info.info(info_load_log_message(request))
        context = {}
        if request.POST:
            form = AdminResponseIssueForm(request.POST)
            if form.is_valid():
                Issue.objects.filter(
                    slug=issue
                ).update(
                    Assign=User.objects.get(username=form.cleaned_data['assign']),
                    Answer=form.cleaned_data['answer'],
                    Status=form.cleaned_data['status'],
                    LastActivity=datetime.datetime.now()
                )
                return redirect(
                    request.META['HTTP_REFERER'],
                    permanent=True
                )
            else:
                context['error'] = _('update_error')
        form = AdminResponseIssueForm(
            {
                'assign': SelectIssue.Assign,
                'status': SelectIssue.Status,
                'answer': SelectIssue.Answer,
            }
        )
        context['form'] = form
        context['issue'] = SelectIssue
        return render(request, 'issues/issue_admin_response.html', context)
    else:
        return redirect(
            reverse(
                'view_issue', kwargs={
                    'issue': SelectIssue.slug
                }
            ),
            permanent=True
        )

@login_required
def view_issue(request, issue):
    try:
        issue = Issue.objects.get(slug=issue)
        if request.user == issue.Autor or request.user.is_staff or request.user.is_superuser:
            logger_info.info(info_load_log_message(request))
            context = {
                'issue': issue,
            }
            return render(request, 'issues/issue.html', context)
        else:
            return redirect(
                reverse('list_issue'),
                permanent=True
            )
    except:
        return redirect(
            reverse('list_issue'),
            permanent=True
        )


@login_required
def reopen_issue(request, issue):
    try:
        issue = Issue.objects.filter(slug=issue)[0]
        if request.user == issue.Autor or request.user.is_staff or request.user.is_superuser:
            logger_info.info(info_load_log_message(request))
            if issue.Status == 'close':
                issue.update(
                    Status="open",
                )
            return redirect(
                reverse(
                    'view_issue',
                    kwargs={
                        'issue': issue.slug,
                    }
                ),
                permanent=True
            )
        else:
            return redirect(
                reverse('list_issue'),
                permanent=True
            )
    except:
        return redirect(
            reverse('list_issue'),
            permanent=True
        )

issues/templates/issues/home.html
{% extends "core/base.html" %}
{% load i18n %}
{% block content %}
    {% if request.user.is_superuser or request.user.is_staff %}
        {% include 'issues/issue_admin.html' with issues=issues %}
    {% else %}
        {% include 'issues/issue_user.html' with issues=issues %}
    {% endif %}
{% endblock %}

issues/templates/issues/issue.html
{% extends "core/base.html" %}
{% load i18n %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'list_issue' %}">{% trans 'list_issue_admin' %}</a></li>
        <li class="active">{{ issue.Title }}</li>
    </ol>
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    {% if issue.Assign %}
                        <p class="pull-left">{% trans 'assign_to' %} {{ issue.Assign }}</p>
                    {% endif %}
                    <p class="pull-right">
                        {% if issue.Status == "open" %}
                            <button type="button" class="btn btn-warning">{% trans 'open' %}</button>
                        {% elif issue.Status == "progress" %}
                            <button type="button" class="btn btn-info">{% trans 'in_progress' %}</button>
                        {% elif issue.Status == "close" %}
                            <button type="button" class="btn btn-success">{% trans 'close' %}</button>
                        {% endif %}
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div>{{ issue.Title }}</div>
                    <blockquote>
                        <p>{{ issue.UserRequest }}</p>
                        <footer><cite title="Source Title">{{ issue.Autor }}</cite> - {{ issue.CreateDate }}</footer>
                    </blockquote>
                </div>
            </div>
            {% if issue.Answer %}
                <div class="row">
                    <div class="col-md-12">
                        <blockquote>
                            <p>{{ issue.Answer }}</p>
                            <footer><cite title="Source Title">{{ issue.Assign }}</cite> - {{ issue.LastActivity }}
                            </footer>
                        </blockquote>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
    {% if issue.Status == "close" %}
        <button class="btn btn-info btn-lg btn-block">
            <a href="{% url 'reopen_issue' issue.slug %}">{% trans "reopen_issue" %}</a>
        </button>
    {% endif %}
{% endblock %}

issues/templates/issues/issue_admin.html
{% load i18n %}
<ol class="breadcrumb">
    <li><a href="{% url 'list_issue' %}">{% trans 'list_issue_admin' %}</a></li>
</ol>
<button class="btn btn-info btn-lg btn-block">
    <a href="{% url 'new_issue' %}">{% trans "new_issue" %}</a>
</button>
{% if issues %}
    <table class="table table-hover">
        <thead>
        <tr>
            <th>{% trans 'title'|capfirst %}</th>
            <th>{% trans 'assign_to'|capfirst %}</th>
            <th>{% trans 'createdate'|capfirst %}</th>
            <th>{% trans 'lastactivity'|capfirst %}</th>
            <th>{% trans 'status'|capfirst %}</th>
        </tr>
        </thead>
        <tbody>
        {% for i in issues %}
            <tr>
                <td><a href="{% url 'respond_issue' i.slug %}">{{ i.Title }}</a></td>
                <td>{% if i.Assign %}{{ i.Assign }}{% endif %}</td>
                <td>{{ i.CreateDate }}</td>
                <td>{{ i.LastActivity }}</td>
                <td>{{ i.Status }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                {% trans 'no_issues' %}
            </div>
        </div>
    </div>
{% endif %}

issues/templates/issues/issue_admin_response.html
{% extends "core/base.html" %}
{% load i18n %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'list_issue' %}">{% trans 'list_issue_admin' %}</a></li>
        <li class="active">{{ issue.Title }}</li>
    </ol>
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div>{{ issue.Title }}</div>
                <blockquote>
                    <p>{{ issue.UserRequest }}</p>
                    <footer><cite title="Source Title">{{ issue.Autor }}</cite> - {{ issue.CreateDate }}</footer>
                </blockquote>
            </div>
            {% if issue.Answer %}
                <div class="row">
                    <div class="col-md-12">
                        <blockquote>
                            <p>{{ issue.Answer }}</p>
                            <footer><cite title="Source Title">{{ issue.Assign }}</cite> - {{ issue.LastActivity }}
                            </footer>
                        </blockquote>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
    {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% endif %}
    <form action="{% url 'respond_issue' issue.slug %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_assign">{{ form.assign.label|capfirst }} </label>
            {{ form.assign }}
        </div>
        <div class="form-group">
            <label for="id_status">{{ form.status.label|capfirst }} </label>
            {{ form.status }}
        </div>
        <div class="form-group">
            <label for="id_answer">{{ form.answer.label|capfirst }} </label>
            {{ form.answer }}
        </div>
        <div class="form-group">
            <input type="submit" value="{% trans 'answer'|capfirst %}" class="btn btn-primary btn-lg btn-block"/>
        </div>
    </form>
{% endblock %}

issues/templates/issues/issue_user.html
{% load i18n %}
<ol class="breadcrumb">
    <li><a href="{% url 'list_issue' %}">{% trans 'list_issue_user' %}</a></li>
</ol>
<button type="button" class="btn btn-info btn-lg btn-block">
    <a href="{% url 'new_issue' %}">{% trans "new_issue" %}</a>
</button>
{% if issues %}
    <table class="table table-hover">
        <thead>
        <tr>
            <th>{% trans 'title'|capfirst %}</th>
            <th>{% trans 'assign_to'|capfirst %}</th>
            <th>{% trans 'createdate'|capfirst %}</th>
            <th>{% trans 'lastactivity'|capfirst %}</th>
            <th>{% trans 'status'|capfirst %}</th>
        </tr>
        </thead>
        <tbody>
        {% for i in issues %}
            <tr>
                <td><a href="{% url 'view_issue' i.slug %}">{{ i.Title }}</a></td>
                <td>{% if i.Assign %}{{ i.Assign }}{% endif %}</td>
                <td>{{ i.CreateDate }}</td>
                <td>{{ i.LastActivity }}</td>
                <td>{{ i.Status }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                {% trans 'no_issues' %}
            </div>
        </div>
    </div>
{% endif %}

issues/templates/issues/send_issue.html
{% extends "core/base.html" %}
{% load i18n %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'list_issue' %}">{% trans 'list_issue' %}</a></li>
        <li class="active">{% trans 'new_issue' %}</li>
    </ol>
    {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% endif %}
    <form action="{% url 'new_issue' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_Issue">{{ form.Title.label|capfirst }} </label>
            {{ form.Title }}
        </div>
        <div class="form-group">
            <label for="id_Issue">{{ form.UserRequest.label|capfirst }} </label>
            {{ form.UserRequest }}
        </div>
        <div class="form-group">
            <input type="submit" value="{% trans 'submit_issue'|capfirst %}" class="btn btn-primary btn-lg btn-block"/>
        </div>
    </form>
{% endblock %}