core/urls.py
# -*-coding:utf-8 -*-
"""
:module: core.urls
:synopsis: root URL for core

:moduleauthor: anthony greau <greau.anthony@gmail.com>
:created: 01/07/2015
:update: 21/07/2015
:var urlpatterns: rooting of urls
"""
from django.conf.urls import patterns
from django.conf.urls import url

from core import home

urlpatterns = patterns('',
                       url(r'^', home.index, name="home"),
                       )

forum/urls.py
# -*-coding:utf-8 -*-
"""
:module: forum.urls
:synopsis: root URL for forum

:moduleauthor: anthony greau <greau.anthony@gmail.com>
:created: 01/07/2015
:update: 21/07/2015
:var urlpatterns: rooting of urls
"""
from django.conf.urls import patterns
from django.conf.urls import url

urlpatterns = patterns('forum.views',
                       url(r'^$', 'display_all', name="forum"),
                       url(r'^(?P<cat>.+)/create/$', 'create_topic', name="create_topic"),
                       url(r'^(?P<cat>.+)/(?P<topic>.+)/edit/(?P<post>.+)/$', 'edit_post', name="edit_post"),
                       url(r'^(?P<cat>.+)/edit/(?P<topic>.+)/$', 'edit_topic', name="edit_topic"),
                       url(r'^(?P<cat>.+)/reply/(?P<topic>.+)/$', 'reply_topic', name="send_reply"),
                       url(r'^(?P<cat>.+)/(?P<topic>.+)/$', 'display_topic', name="topic_cat"),
                       url(r'^(?P<cat>.+)/$', 'display_cat', name="cat"),
                       )

framework/urls.py
from django.conf import settings
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = patterns('',
                       url(r'^$', include('core.urls')),
                       url(r'', include('contact.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^forum/', include('forum.urls')),
                       url(r'^hijack/', include('hijack.urls')),
                       url(r'^i18n/', include('django.conf.urls.i18n')),
                       url(r'^issue/', include('issues.urls')),
                       url(r'^ldap/', include('ldap42.urls')),
                       url(r'^log/', include('generate_logs.urls')),
                       url(r'^profil/', include('profil.urls')),
                       ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.MEDIA_ROOT})
                            )

forum/models.py
# -*-coding:utf-8 -*-
"""
:module: forum.models
:synopsis: define storage models for forum

:moduleauthor: anthony greau <greau.anthony@gmail.com>
:created: 01/07/2015
:update: 21/07/2015
"""

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

from autoslug import AutoSlugField


class ForumCat(models.Model):
    """define the storage of category

    :param models.Model: contain all function for define a storage
    :type models.Model: models object
    :var Name: content the name of the category
    :var slug: content the slug of the category
    :return: ForumCat object
    :rtype: object
    """
    Name = models.CharField(max_length=50)
    slug = AutoSlugField(populate_from=_('Name'))

    def __str__(self):
        return self.Name


class ForumTopic(models.Model):
    """define the storage of topics

    :param models.Model: contain all function for define a storage
    :type models.Model: models object
    :var CatParent: content the object of the parent category
    :var Title: title of topic
    :var slug: access slug of the topic
    :var Autor: user object of the autor
    :var Message: content of the topic
    :var CreateDate: create date of the topic
    :var LastModified: last modify date of the topic
    :var LastReply: last reply date of the topic
    :return: ForumTopic object
    :rtype: object
    """
    CatParent = models.ForeignKey(ForumCat, related_name=_("categorie_parente"))
    Title = models.CharField(max_length=50)
    slug = AutoSlugField(populate_from='Title')
    Autor = models.ForeignKey(User)
    Message = models.TextField()
    CreateDate = models.DateTimeField(auto_now_add=True)
    LastModified = models.DateTimeField(auto_now_add=True)
    LastReply = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Title


class ForumPost(models.Model):
    """define the storage of post

    :param models.Model: contain all function for define a storage
    :type models.Model: models object
    :var TopicParent: content the object of the parent topic
    :var Autor: user object of the autor
    :var Message: content of the post
    :var CreateDate: create date of the post
    :var LastModified: last modify date of the post
    :return: ForumPost object
    :rtype: object
    """
    TopicParent = models.ForeignKey(ForumTopic, null=True)
    Autor = models.ForeignKey(User)
    Message = models.TextField()
    CreateDate = models.DateTimeField(auto_now_add=True)
    LastModified = models.DateTimeField(auto_now_add=True)

forum/forms/CreateTopic.py
# -*-coding:utf-8 -*-
"""
:module: forum.forms.CreateTopic
:synopsis: generate the forum for create a new topic

:moduleauthor: anthony greau <greau.anthony@gmail.com>
:created: 01/07/2015
:update: 21/07/2015
:seealso: forum.moodels.ForumTopic
"""
from django import forms
from django.utils.translation import ugettext as _

from forum.models import ForumTopic


class TopicForm(forms.Form, forms.ModelForm):
    """
    this class define field of create topic form

    :param forms.Form: contain all function for define a field
    :type forms.Form: form object
    :param forms.ModelForm: contain all function for generate form from model
    :type forms.ModelForm: object
    :var title: title of topic
    :var content: content of topic
    :return: None
    :rtype: None
    """

    class Meta:
        model = ForumTopic
        fields = [
            'Title',
            'Message',
        ]

    Title = forms.CharField(
        label=_("title"),
        widget=forms.TextInput(
            attrs={
                'class': "form-control",
                'placeholder': _("title")
            },
        ),
    )

    Message = forms.CharField(
        label=_("message"),
        widget=forms.Textarea(
            attrs={
                'class': "form-control",
                'placeholder': _("message")
            },
        ),
    )

forum/forms/ReplyTopic.py
# -*-coding:utf-8 -*-
"""
:module: forum.forms.ReplyTopic
:synopsis: generate the forum for reply of a topic

:moduleauthor: anthony greau <greau.anthony@gmail.com>
:created: 01/07/2015
:update: 21/07/2015
:seealso: forum.moodels.ForumPost
"""
from django import forms
from django.utils.translation import ugettext as _

from forum.models import ForumPost


class PostForm(forms.Form, forms.ModelForm):
    """
    this class define field of create topic form

    :param forms.Form: contain all function for define a field
    :type forms.Form: form object
    :param forms.ModelForm: contain all function for generate form from model
    :type forms.ModelForm: object
    :var content: content of topic
    :return: None
    :rtype: None
    """

    class Meta:
        model = ForumPost
        fields = [
            'Message',
        ]

    Message = forms.CharField(
        label=_("message"),
        widget=forms.Textarea(
            attrs={
                'class': "form-control",
                'placeholder': _("reponse")
            },
        ),
    )

forum/views.py
# -*-coding:utf-8 -*-
"""
:module: forum.views
:synopsis: generate all content of forum

:moduleauthor: anthony greau <greau.anthony@gmail.com>
:created: 01/07/2015
:update: 21/07/2015
:var logger_error: logger error
:var logger_info: logger info
:seealso: forum.models
:seealso: forum.forms.CreateTopic.TopicForm
:seealso: forum.forms.ReplyTopic.PostForm
:seealso: generate_logs.functions.info_load_log_message
"""
import datetime
import logging

from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from django.utils.translation import ugettext as _

from django.utils.text import slugify

from forum import models
from generate_logs.functions import info_load_log_message
from forum.forms.CreateTopic import TopicForm
from forum.forms.ReplyTopic import PostForm

logger_info = logging.getLogger('info')
logger_error = logging.getLogger('error')


@login_required
def display_all(request):
    """display forum's category

    :param request: object contain context of request
    :type request: object
    :return: HTTPResponse
    """
    logger_info.info(info_load_log_message(request))
    return render(
        request,
        "forum/home.html", {
            'cat': models.ForumCat.objects.all().order_by('Name'),
        }
    )


@login_required
def display_cat(request, cat):
    """display category's topic list

    :param request: object contain context of request
    :type request: object
    :param cat: slug of categorie
    :type cat: slug
    :return: HTTPResponse
    """
    logger_info.info(info_load_log_message(request))
    try:
        cat = models.ForumCat.objects.get(slug=cat)
        last_mod = models.ForumTopic.objects.filter(
            CatParent=cat
        ).order_by('LastReply').order_by('CreateDate').reverse()
        return render(
            request,
            "forum/cat.html", {
                'cat': cat,
                'last_mod': last_mod,
            }
        )
    except:
        return display_all(request)


@login_required
def display_topic(request, cat, topic):
    """display category's topic list

    :param request: object contain context of request
    :type request: object
    :param cat: slug of categorie
    :type cat: slug
    :param topic: slug of topic
    :type topic: slug
    :var cat: get the the selected category
    :var thr: get the first message of the topic
    :var post: get lit of related post of thr
    :return: HTTPResponse
    """
    logger_info.info(info_load_log_message(request))
    try:
        cat = models.ForumCat.objects.filter(slug=cat)[0]
        try:
            thr = models.ForumTopic.objects.get(slug=topic)
            post = models.ForumPost.objects.filter(TopicParent=thr)
            return render(
                request,
                "forum/topic.html", {
                    'cat': cat,
                    'topic': thr,
                    'posts': post,
                    'reply': PostForm(),
                }
            )
        except:
            return display_cat(request, cat)
    except:
        return display_all(request)


@login_required
def create_topic(request, cat):
    """create new topic

    :param request: object contain context of request
    :type request: object
    :param cat: slug of categorie
    :type cat: slug
    :var cat: categorie object selected by slug
    :var form: form for create topic
    :var errors: dict of process error
    :var create: new topic
    :var topic: get the new topic
    :var context: define the context for display page
    :return: HTTPResponse
    """
    logger_info.info(info_load_log_message(request))
    cat = models.ForumCat.objects.get(slug=cat)
    form = TopicForm(request.POST)
    error = {}
    if request.method == 'POST':
        if form.is_valid():
            try:
                create = models.ForumTopic(
                    CatParent=cat,
                    Title=form.cleaned_data['Title'],
                    Autor=request.user,
                    Message=form.cleaned_data['Message'],
                ).save()
                if create is None:
                    topic = models.ForumTopic.objects.filter(
                        Title=form.cleaned_data['Title']
                    ).filter(
                        Autor=request.user
                    ).filter(
                        Message=form.cleaned_data['Message']
                    )[0]
                    return redirect(
                        reverse(
                            'topic_cat',
                            kwargs={
                                'cat': cat.slug,
                                'topic': topic.slug,
                            }
                        ),
                        permanent=True
                    )
            except:
                logger_error.error(_('save_topic'))
                error['save_topic'] = _('topic_fail')
        else:
            if not request.POST['Title']:
                error['no_title'] = _("topic_must_contain_title")
            if not request.POST['Message']:
                error['no_title'] = _("topic_must_contain_message")
    context = {
        'cat': cat,
        'form': form,
        'error': error,
    }
    return render(
        request,
        "forum/create_topic.html",
        context,
    )


@login_required
def reply_topic(request, cat, topic):
    """save new reply

    :param request: object contain context of request
    :type request: object
    :param cat: slug of categorie
    :type cat: slug
    :var topic: topic slug
    :type topic: slug
    :var form: form for topic reply
    :var top: get the new topic
    :return: HTTPResponse
    """
    logger_info.info(info_load_log_message(request))
    form = PostForm(request.POST)
    top = models.ForumTopic.objects.get(slug=topic)
    if form.is_valid():
        models.ForumPost(
            TopicParent=top,
            Autor=request.user,
            Message=form.cleaned_data['Message'],
        ).save()
        models.ForumTopic.objects.filter(
            slug=topic
        ).update(
            LastReply=timezone.now()
        )
        return redirect(
            request.META['HTTP_REFERER'],
            permanent=True
        )
    else:
        if top.CatParent:
            return redirect(
                reverse(
                    'topic_cat',
                    kwargs={
                        'cat': cat.slug,
                        'topic': topic.slug,
                    }
                ),
                permanent=True
            )
        else:
            return display_all(request)


@login_required
def edit_topic(request, cat, topic):
    """display process for edit topic

    :param request: object contain context of request
    :type request: object
    :param cat: slug of categorie
    :type cat: slug
    :param topic: slug of topic
    :type topic: slug
    :var cat: select category by slug
    :return: HTTPResponse
    """
    logger_info.info(info_load_log_message(request))
    try:
        cat = models.ForumCat.objects.get(slug=cat)
        wrong_cat = 0
    except:
        wrong_cat = 1
    try:
        models.ForumTopic.objects.get(slug=topic)
        wrong_topic = 0
    except:
        wrong_topic = 1
    if not wrong_cat and not wrong_topic and request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            update = models.ForumTopic.objects.filter(slug=topic).update(
                Title=form.cleaned_data['Title'],
                Autor=request.user,
                slug=slugify(form.cleaned_data['Title']),
                Message=form.cleaned_data['Message'],
                LastModified=timezone.now()
            )
            if update is not None:
                topic = models.ForumTopic.objects.filter(
                    Title=form.cleaned_data['Title']
                ).filter(
                    Autor=request.user
                ).filter(
                    Message=form.cleaned_data['Message']
                )
                return redirect(
                    reverse(
                        'topic_cat',
                        kwargs={
                            'cat': cat.slug,
                            'topic': topic[0].slug
                        }
                    ),
                    permanent=True
                )
            else:
                context = {
                    'cat': cat,
                    'error': _('thread_fail'),
                    'form': form
                }
        else:
            top = models.ForumTopic.objects.get(slug=topic)
            form = TopicForm(
                {
                    'Title': top.Title,
                    'Message': top.Message
                }
            )
            context = {
                'cat': cat,
                'form': form
            }
    elif wrong_cat and wrong_topic:
        return redirect(
            reverse('forum'),
            permanent=True
        )
    elif wrong_cat:
        top = models.ForumTopic.objects.get(slug=topic)
        return redirect(
            reverse(
                'edit_topic', kwargs={
                    'cat': top.CatParent.slug,
                    'topic': top.slug
                }
            ),
            permanent=True
        )
    elif wrong_topic:
        return redirect(
            reverse(
                'cat', kwargs={
                    'cat': cat
                }
            ),
            permanent=True
        )
    else:

forum/templates/forum/cat.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'forum' %}">{% trans 'forum' %}</a></li>
        <li class="active">{{ cat.Name }}</li>
    </ol>
    <div class="row">
        <div class="col-md-12">
            <button type="button" class="btn btn-info btn-lg btn-block">
                <a href="{% url 'create_topic' cat.slug %}">{% trans "new_topic" %}</a>
            </button>
        </div>
    </div>
    <table class="table table-condensed">
        {% for tc in last_mod %}
            <tr>
                <td>
                    <div class="row">
                        <div class="col-md-1">
                            <img src="http://thumbs.dreamstime.com/x/avatar-inconnu-d-homme-d-affaires-35616527.jpg"
                                 class="img-circle" height="50" widtrh="50">
                        </div>
                        <div class="col-md-11">
                            <div class="row">
                                <div class="col-md-12">
                                    <a href="{{ tc.slug }}">{{ tc.Title }}</a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    {% if LastReply %}
                                        {% trans 'last_mod' %} {% trans 'by' %} {{ tc.Autor }} {% trans 'at' %}
                                        {{ tc.LastReply }}
                                    {% else %}
                                        {% trans 'last_mod' %} {% trans 'by' %} {{ tc.Autor }} {% trans 'at' %}
                                        {{ tc.CreateDate }}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

forum/templates/forum/create_topic.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'forum' %}">{% trans 'forum' %}</a></li>
        <li><a href="{% url 'cat' cat.slug %}">{{ cat.Name }}</a></li>
        {% if edit %}
            <li class="active">{% trans "edit_topic" %}</li>
        {% else %}
            <li class="active">{% trans "new_topic" %}</li>
        {% endif %}
    </ol>
    {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% endif %}
    {% if info %}
        <div class="alert alert-success" role="alert">
            {{ info }}
        </div>
    {% endif %}
    <form action="{{ request.path }}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_Title">{{ form.Title.label|capfirst }} </label>
            {{ form.Title }}
        </div>
        <div class="form-group">
            <label for="id_Message">{{ form.Message.label|capfirst }} </label>
            {{ form.Message }}
        </div>
        <div class="form-group">
            <input type="submit" value="{% trans 'create_topic'|capfirst %}" class="btn btn-primary btn-lg btn-block"/>
        </div>
    </form>
{% endblock %}

forum/templates/forum/edit_post.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'forum' %}">{% trans 'forum' %}</a></li>
        <li><a href="{% url 'cat' cat.slug %}">{{ cat.Name }}</a></li>
        <li class="active">{% trans "edit_post" %}</li>
    </ol>
    {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
    {% endif %}
    <form action="{% url 'edit_post' cat.slug topic post %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_Message">{{ form.Message.label|capfirst }} </label>
            {{ form.Message }}
        </div>
        <div class="form-group">
            <input type="submit" value="{% trans 'edit_post'|capfirst %}" class="btn btn-primary btn-lg btn-block"/>
        </div>
    </form>
{% endblock %}

forum/templates/forum/home.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block content %}
    <ol class="breadcrumb">
        <li class="active">{% trans 'forum' %}</li>
    </ol>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="jumbotron">
                <div class="container">
                    <div class="row">
                        {% if cat %}
                            {% for c in cat %}
                                <div class="col-md-3">
                                    <a href="{{ c.slug }}">{{ c.Name }}</a>
                                </div>
                                {% if forloop.counter|divisibleby:4 %}
                                    </div>
                                    <div class="row">
                                {% endif %}
                            {% endfor %}
                        {% else %}
                            <div class="alert alert-info" role="alert">{% trans "no_category" %}</div>
                        {% endif %}
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

forum/templates/forum/response.html
{% load i18n %}
<form action="{% url 'send_reply' cat topic %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        {{ form.Message }}
    </div>
    <div class="form-group">
        <input type="submit" value="{% trans 'response_topic'|capfirst %}" class="btn btn-primary btn-lg btn-block"/>
    </div>
</form>

forum/templates/forum/topic.html
{% extends 'core/base.html' %}
{% load i18n %}
{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'forum' %}">{% trans 'forum' %}</a></li>
        <li><a href="{% url 'cat' cat.slug %}">{{ cat.Name }}</a></li>
        <li class="active">{{ topic.Title }}</li>
    </ol>
    <div class="list-group">
        <div class="row">
            <div class="col-md-1">
                <img src="http://thumbs.dreamstime.com/x/avatar-inconnu-d-homme-d-affaires-35616527.jpg"
                     class="img-circle" height="50" widtrh="50">
            </div>
            <div class="col-md-10">
                <div class="row">
                    <div class="col-md-12">
                        {{ topic.Message }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        {{ topic.Autor }}
                        - {{ topic.CreateDate|date:"d/m/Y" }} {% trans "at" %} {{ topic.CreateDate|date:"H:i:s" }}
                    </div>
                </div>
            </div>
            <div class="col-md-1">
                <a href="{% url "edit_topic" cat=cat.slug topic=topic.slug %}">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
            </div>
        </div>
        {% if posts %}
            {% for p in posts %}
                <div class="row">
                    <div class="col-md-1 pull-center">
                        <img src="http://thumbs.dreamstime.com/x/avatar-inconnu-d-homme-d-affaires-35616527.jpg"
                             class="img-circle" height="50" widtrh="50">
                    </div>
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col-md-12">
                                {{ p.Message }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                {{ p.Autor }}
                                - {{ p.CreateDate|date:"d/m/Y" }} {% trans "at" %} {{ p.CreateDate|date:"H:i:s" }}
                            </div>
                        </div>
                        {% if  p.CreateDate < p.LastModified %}
                            <div class="row">
                                <div class="col-md-12">
                                    {% trans 'modify_by' %} {{ p.Autor }}
                                    - {{ p.LastModified|date:"d/m/Y" }} {% trans "at" %} {{ p.LastModified|date:"H:i:s" }}
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-md-1">
                        <a href="{% url "edit_post" cat=cat.slug topic=topic.slug post=p.pk %}">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    {% include "forum/response.html" with form=reply cat=cat.slug topic=topic.slug %}
{% endblock %}